### ISSUE TITLE
Cannot compil with java 1.8

### ISSUE THREAD

**Issue by lmanchon** [teerjk/VarSifter#2]
--Hi,

it seems that it can't compile with java 1.8, have you already test it ?
Thank you --

/home/save/jdk1.8.0_102/bin/javac -J-Xmx1G -source 1.8 -bootclasspath "/home/save/jdk1.8.0_102/jre/lib/rt.jar" -cp jung/*:. -Xlint:unchecked -target 1.8 VarSifter.java
./components/TableSorter.java:107: warning: [unchecked] unchecked call to compareTo(T) as a member of the raw type Comparable
            return ((Comparable) o1).compareTo(o2);
                                              ^
  where T is a type-variable:
    T extends Object declared in interface Comparable
./components/TableSorter.java:216: warning: [unchecked] unchecked call to add(E) as a member of the raw type List
            sortingColumns.add(new Directive(column, status));
                              ^
  where E is a type-variable:
    E extends Object declared in interface List
./components/TableSorter.java:238: warning: [unchecked] unchecked call to put(K,V) as a member of the raw type Map
            columnComparators.put(type, comparator);
                                 ^
  where K,V are type-variables:
    K extends Object declared in interface Map
    V extends Object declared in interface Map
./components/TableSorter.java:342: warning: [unchecked] unchecked call to compare(T,T) as a member of the raw type Comparator
                    comparison = getComparator(column).compare(o1, o2);
                                                              ^
  where T is a type-variable:
    T extends Object declared in interface Comparator
./CustomQueryView.java:78: warning: [unchecked] unchecked call to JList(E[]) as a member of the raw type JList
    private JList fixedSampleList = new JList(fixedSamples);
                                    ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:173: warning: [unchecked] unchecked method invocation: method setEdgeShapeTransformer in interface RenderContext is applied to given types
        vv.getRenderContext().setEdgeShapeTransformer(new EdgeShape.Line());
                                                     ^
  required: Transformer<Context<Graph<V,E>,E>,Shape>
  found: Line
  where V,E are type-variables:
    V extends Object declared in interface RenderContext
    E extends Object declared in interface RenderContext
./CustomQueryView.java:173: warning: [unchecked] unchecked conversion
        vv.getRenderContext().setEdgeShapeTransformer(new EdgeShape.Line());
                                                      ^
  required: Transformer<Context<Graph<V,E>,E>,Shape>
  found:    Line
  where V,E are type-variables:
    V extends Object declared in interface RenderContext
    E extends Object declared in interface RenderContext
./CustomQueryView.java:185: warning: [unchecked] unchecked call to JList(E[]) as a member of the raw type JList
        sampleList = new JList(sampleNames);
                     ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:186: warning: [unchecked] unchecked call to JList(E[]) as a member of the raw type JList
        annotList = new JList(annotNames);
                    ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:703: warning: [unchecked] unchecked call to setListData(E[]) as a member of the raw type JList
                            stringAnnotList.setListData(currentMap.getSortedEntries());
                                                       ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:780: warning: [unchecked] unchecked call to setListData(E[]) as a member of the raw type JList
                            stringAnnotList.setListData(new String[]{""});
                                                       ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:807: warning: [unchecked] unchecked call to setListData(E[]) as a member of the raw type JList
        stringAnnotList.setListData(new String[]{""});
                                   ^
  where E is a type-variable:
    E extends Object declared in class JList
./CustomQueryView.java:1047: warning: [unchecked] unchecked cast
                    graph = (DelegateForest<CustomVertex,Integer>)ois.readObject();
                                                                                ^
  required: DelegateForest<CustomVertex,Integer>
  found:    Object
./CustomQueryView.java:1049: warning: [unchecked] unchecked cast
                        bitSetList = (ArrayList<BitSet>)ois.readObject();
                                                                      ^
  required: ArrayList<BitSet>
  found:    Object
14 warnings

**Comment by teerjk** [comment]
No, I haven't had a chance to test under Java 1.8. However, it looks like these are all warnings, but not actually errors? Is a jar file created?

**Comment by lmanchon** [comment]
unfortunaly not, also i have tested with Java 1.7 and again same warnings and jar file not created.

**Comment by teerjk** [comment]
Sorry, I mispoke: the javac step should produce .class files. I have checked in 1.7, and I do see many warnings (some of which are in external code I am using). However, the .class files are created, and a jar can be created using the java 'jar' command (see the Makefile for the settings I use.) I cannot test with 1.8 at the moment, but do look to see if the .class files are made.

**Comment by lmanchon** [comment]
yas, this is what i have done with jar command: jar -cv0mf manifest.txt $@ @$(CLASS_LIST) -J-Xmx500M;
but then it failed with: java -jar VarSifter.jar

Exception in thread "main" java.lang.UnsupportedClassVersionError: VarSifter : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

try to send me your VarSifter.jar, to see if it runs on my computer.

thanks.

**Comment by teerjk** [comment]
Very strange: this error indicates that an older Java version is attempting to execute code complied by a newer Java version. Try 'java -version' to confirm the version of your JVM, and then use the javac -target option to target that version.
Also, hopefully you found the pre-compiled binary releases:
https://github.com/teerjk/VarSifter/releases
I believe I've compiled these with 1.7.

**Comment by lmanchon** [comment]
this is the command i use to compil: 
javac -J-Xmx1G -source 1.7 -bootclasspath /usr/java/jre1.7.0_65/lib/rt.jar -cp jung/*:. -target 1.7 VarSifter.java
it returns that:
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

so i have added -Xlint:unchecked and now it sounds good.

your compiled releases 1.7/1.8 seems to work fine for me.

thank you for your help.

**Comment by teerjk** [comment]
While I should address these compile warnings, they don't usually prevent compilation. Glad the "releases" binaries work for you!
