### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by kose-bioinfo** [teerjk/VarSifter#4]
Hi,

I am unable to download the latest version 1.9. I am not given access to the bitbucket file. I get the following error:

command: 
hg clone https://bitbucket.org/teerjk/varsifter/

http authorization required for https://bitbucket.org/teerjk/varsifter/
realm: Bitbucket.org HTTP

**Comment by teerjk** [comment]
Looks like I need to update the documentation. VarSifter is now hosted on github. You can either download the compiled version from the "releases" link, or the source code from any release.
